-- Categorization flow (#13) — implementation plan Decision 15 / Seed Data.
--
-- A small, hand-written, reviewed DELTA of `INSERT OR REPLACE` statements. It assumes a
-- bootstrapped store (schema + starter seeds already present, i.e. `ensureDatabaseReady()` has
-- already run at least once) and adds one connection, one product, two merchants, four pending
-- movements and nine already-categorized movements. Ids are literal and prefixed `stage-`, so the
-- file is diffable and idempotent — re-applying it is a no-op.
--
-- Every column this file writes for a `transactions` row is either a bank-owned fact or, for the
-- nine history rows, a person-owned column the fixture itself sets deliberately (`category_source
-- = 'user'`) to exercise the "used categories" chip ordering. No row here sets `included_amount`
-- or `excluded_at` — an exclusion made during a smoke run is unambiguously the tester's own
-- (implementation plan Seed Data section).

INSERT OR REPLACE INTO "user_financial_institutions" ("id", "financial_institution_id", "status", "credentials_key", "sync_status", "last_sync_at", "last_success_at", "last_error_code", "last_error_message", "created_at") VALUES ('stage-connection', 'banco-de-chile', 'active', 'secure-store-key-stage-connection', 'idle', '2026-01-27T21:05:00.000Z', '2026-01-27T21:05:00.000Z', NULL, NULL, '2026-01-01T00:00:00.000Z');

INSERT OR REPLACE INTO "user_financial_products" ("id", "user_financial_institution_id", "external_id", "type", "name", "currency_code", "assets", "metadata", "updated_at") VALUES ('stage-product', 'stage-connection', 'stage-checking-001', 'checking', 'Cuenta Corriente', 'CLP', NULL, NULL, '2026-01-01T00:00:00.000Z');

INSERT OR REPLACE INTO "merchants" ("id", "name", "assets", "transaction_category_id", "country_code", "user_id", "created_at") VALUES ('stage-merchant-mercadolibre', 'MercadoLibre Chile', NULL, 'compras', 'CL', NULL, '2026-01-01T00:00:00.000Z');
INSERT OR REPLACE INTO "merchants" ("id", "name", "assets", "transaction_category_id", "country_code", "user_id", "created_at") VALUES ('stage-merchant-consultoria', 'Consultoría Digital SpA', NULL, 'freelance', 'CL', NULL, '2026-01-01T00:00:00.000Z');

-- Pending movements (4) — no category, not excluded. Newest first by date_local: income (27),
-- expense (26), no-merchant (25), plain (24) — this is the order `listPendingBatch` returns.
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-income', 'stage-product', 'stage-ext-income', 'stage-dedup-income', 1200000, 'credit', 'CLP', '2026-01-27T21:00:00.000Z', '2026-01-27', 'TRANSFERENCIA ELECTRONICA PAGO CONSULTORIA DESARROLLO WEB', NULL, 'stage-merchant-consultoria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-27T21:00:00.000Z', '2026-01-27T21:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-expense', 'stage-product', 'stage-ext-expense', 'stage-dedup-expense', 42000, 'debit', 'CLP', '2026-01-26T14:32:00.000Z', '2026-01-26', 'MERCADOLIBRE COMPRA ONLINE PRODUCTO ELECTRONICO', NULL, 'stage-merchant-mercadolibre', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-26T14:32:00.000Z', '2026-01-26T14:32:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-nomerchant', 'stage-product', 'stage-ext-nomerchant', 'stage-dedup-nomerchant', 8990, 'debit', 'CLP', '2026-01-25T12:00:00.000Z', '2026-01-25', 'COMERCIO SIN IDENTIFICAR 4523', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-25T12:00:00.000Z', '2026-01-25T12:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-plain', 'stage-product', 'stage-ext-plain', 'stage-dedup-plain', 15500, 'debit', 'CLP', '2026-01-24T10:00:00.000Z', '2026-01-24', 'FARMACIA CENTRO LOCAL 12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-24T10:00:00.000Z', '2026-01-24T10:00:00.000Z');

-- Already-categorized history (9) — `category_source = 'user'` so the chip grid's "most used"
-- ordering has something to read (Decision 6). Six expense categories (one movement each) and
-- two income categories (sueldo x2, ingresos-extra x1) — none of them `compras` or `freelance`,
-- so the suggested chip (Decision 6 step 1) never collides with the used-categories list.
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-comida', 'stage-product', 'stage-ext-history-comida', 'stage-dedup-history-comida', 12000, 'debit', 'CLP', '2026-01-18T13:00:00.000Z', '2026-01-18', 'RESTAURANT EL BUEN SABOR', NULL, NULL, 'comida', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-18T13:00:00.000Z', '2026-01-18T13:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-supermercado', 'stage-product', 'stage-ext-history-supermercado', 'stage-dedup-history-supermercado', 35000, 'debit', 'CLP', '2026-01-17T11:00:00.000Z', '2026-01-17', 'SUPERMERCADO LOCAL', NULL, NULL, 'supermercado', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-17T11:00:00.000Z', '2026-01-17T11:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-transporte', 'stage-product', 'stage-ext-history-transporte', 'stage-dedup-history-transporte', 8000, 'debit', 'CLP', '2026-01-16T08:00:00.000Z', '2026-01-16', 'METRO DE SANTIAGO', NULL, NULL, 'transporte', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-16T08:00:00.000Z', '2026-01-16T08:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-entretenimiento', 'stage-product', 'stage-ext-history-entretenimiento', 'stage-dedup-history-entretenimiento', 15000, 'debit', 'CLP', '2026-01-15T20:00:00.000Z', '2026-01-15', 'CINE PLANETA', NULL, NULL, 'entretenimiento', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-15T20:00:00.000Z', '2026-01-15T20:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-servicios', 'stage-product', 'stage-ext-history-servicios', 'stage-dedup-history-servicios', 45000, 'debit', 'CLP', '2026-01-14T09:00:00.000Z', '2026-01-14', 'CUENTA DE LUZ', NULL, NULL, 'servicios', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-14T09:00:00.000Z', '2026-01-14T09:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-salud', 'stage-product', 'stage-ext-history-salud', 'stage-dedup-history-salud', 20000, 'debit', 'CLP', '2026-01-13T15:00:00.000Z', '2026-01-13', 'FARMACIA CRUZ VERDE', NULL, NULL, 'salud', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-13T15:00:00.000Z', '2026-01-13T15:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-sueldo-1', 'stage-product', 'stage-ext-history-sueldo-1', 'stage-dedup-history-sueldo-1', 1500000, 'credit', 'CLP', '2026-01-05T09:00:00.000Z', '2026-01-05', 'PAGO SUELDO ENERO', NULL, NULL, 'sueldo', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-05T09:00:00.000Z', '2026-01-05T09:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-sueldo-2', 'stage-product', 'stage-ext-history-sueldo-2', 'stage-dedup-history-sueldo-2', 1450000, 'credit', 'CLP', '2025-12-05T09:00:00.000Z', '2025-12-05', 'PAGO SUELDO DICIEMBRE', NULL, NULL, 'sueldo', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2025-12-05T09:00:00.000Z', '2025-12-05T09:00:00.000Z');
INSERT OR REPLACE INTO "transactions" ("id", "user_financial_product_id", "external_id", "dedup_hash", "amount", "type", "currency_code", "occurred_at", "date_local", "raw_description", "note", "merchant_id", "transaction_category_id", "category_source", "review_flag", "excluded_at", "exclusion_reason", "exclusion_note", "included_amount", "metadata", "is_manual", "created_at", "updated_at") VALUES ('stage-tx-history-ingresos-extra', 'stage-product', 'stage-ext-history-ingresos-extra', 'stage-dedup-history-ingresos-extra', 100000, 'credit', 'CLP', '2026-01-10T10:00:00.000Z', '2026-01-10', 'REEMBOLSO SEGURO DE SALUD', NULL, NULL, 'ingresos-extra', 'user', NULL, NULL, NULL, NULL, NULL, NULL, 0, '2026-01-10T10:00:00.000Z', '2026-01-10T10:00:00.000Z');
