/**
 * Typed mirror of `design/tokens.json` plus component geometry read off the mockup's `mu-*`
 * CSS (`design/mockups/mobile/index.html`).
 *
 * This file is hand-written, not generated, and is parity-tested by
 * `apps/mobile/src/__tests__/theme-tokens-parity.test.ts`: `theme` must deep-equal
 * `design/tokens.json` (excluding `$`-prefixed metadata keys and the `categoryLabels` group,
 * which is copy, not a visual token — see the implementation plan's Decision 1).
 *
 * `theme` and `componentMetrics` together are the **only** place a hex color, spacing value,
 * radius, or other visual-style number literal may live in `apps/mobile` (AC1). Everywhere
 * else, `apps/mobile/src/__tests__/no-style-literals.test.ts` enforces this by scanning
 * `apps/mobile/app/**` and `apps/mobile/src/**` for such literals.
 *
 * See the implementation plan for the full rationale:
 * docs/specs/developments/20260801172100_2-theme-design-system-primitives/
 * 2_2-theme-design-system-primitives_implementation-plan.md
 * → Decision 1 (theme.ts is generated by hand, parity-tested by machine)
 * → Decision 2 (theme vs componentMetrics)
 */

/**
 * Verbatim mirror of `design/tokens.json`'s ten mirrored top-level groups (Decision 1).
 * `categoryLabels` (es/en display copy for seeded categories) is intentionally excluded — no
 * primitive reads it, and copy does not belong in the theme (Decision 3).
 */
export const theme = {
  colors: {
    brandPrimary: '#6366f1',
    brandPrimaryDark: '#4f46e5',
    brandPrimaryDarker: '#4338ca',
    brandSecondary: '#f59e0b',
    celebration: '#8b5cf6',
    tabBar: '#ffffff',
    tabBarActive: '#6366f1',
    tabBarInactive: '#64748b',
    surface0: '#fafbfc',
    surface1: '#ffffff',
    surface2: '#f8fafc',
    surface3: '#f1f5f9',
    textPrimary: '#1a1d29',
    textSecondary: '#64748b',
    textTertiary: '#94a3b8',
    textBrand: '#6366f1',
    textOnBrand: '#ffffff',
    border: '#e2e8f0',
    borderInput: '#d1d5db',
    ring: '#6366f1',
    success: '#10b981',
    successBg: '#ecfdf5',
    successBorder: '#d1fae5',
    warning: '#f59e0b',
    warningBg: '#fffbeb',
    warningBorder: '#fef3c7',
    danger: '#ef4444',
    dangerBg: '#fef2f2',
    dangerBorder: '#fee2e2',
    info: '#6366f1',
    infoBg: '#eef2ff',
    infoBorder: '#e0e7ff',
    celebrationBg: '#f5f3ff',
    celebrationBorder: '#ede9fe',
    overlayScrim: 'rgba(15, 23, 42, 0.45)',
    focusRing: 'rgba(99, 102, 241, 0.12)',
    onGradientSurface: 'rgba(255, 255, 255, 0.2)',
    onGradientDecoration: 'rgba(255, 255, 255, 0.12)',
    switchTrackOff: '#e5e7eb',
    palette: {
      indigo: {
        '50': '#eef2ff',
        '100': '#e0e7ff',
        '200': '#c7d2fe',
        '300': '#a5b4fc',
        '400': '#818cf8',
        '500': '#6366f1',
        '600': '#4f46e5',
        '700': '#4338ca',
        '800': '#3730a3',
        '900': '#312e81',
      },
      amber: {
        '50': '#fffbeb',
        '100': '#fef3c7',
        '200': '#fde68a',
        '300': '#fcd34d',
        '400': '#fbbf24',
        '500': '#f59e0b',
        '600': '#d97706',
        '700': '#b45309',
        '800': '#92400e',
        '900': '#78350f',
      },
      emerald: {
        '50': '#ecfdf5',
        '100': '#d1fae5',
        '200': '#a7f3d0',
        '300': '#6ee7b7',
        '400': '#34d399',
        '500': '#10b981',
        '600': '#059669',
        '700': '#047857',
        '800': '#065f46',
        '900': '#064e3b',
      },
      red: {
        '50': '#fef2f2',
        '100': '#fee2e2',
        '200': '#fecaca',
        '300': '#fca5a5',
        '400': '#f87171',
        '500': '#ef4444',
        '600': '#dc2626',
        '700': '#b91c1c',
        '800': '#991b1b',
        '900': '#7f1d1d',
      },
      violet: {
        '50': '#f5f3ff',
        '100': '#ede9fe',
        '200': '#ddd6fe',
        '300': '#c4b5fd',
        '400': '#a78bfa',
        '500': '#8b5cf6',
        '600': '#7c3aed',
        '700': '#6d28d9',
        '800': '#5b21b6',
        '900': '#4c1d95',
      },
      slate: {
        '50': '#f8fafc',
        '100': '#f1f5f9',
        '200': '#e2e8f0',
        '300': '#cbd5e1',
        '400': '#94a3b8',
        '500': '#64748b',
        '600': '#475569',
        '700': '#334155',
        '800': '#1e293b',
        '900': '#1a1d29',
      },
    },
  },
  gradients: {
    challenge: { angle: 135, from: '#8b5cf6', to: '#6366f1' },
    income: { angle: 135, from: '#34d399', to: '#10b981' },
    expense: { angle: 135, from: '#fbbf24', to: '#f59e0b' },
    celebration: { angle: 135, from: '#a78bfa', to: '#6366f1' },
    brand: { angle: 135, from: '#6366f1', to: '#4f46e5' },
  },
  chart: {
    series: ['#6366f1', '#f59e0b', '#10b981', '#ef4444', '#8b5cf6'],
    grid: '#e2e8f0',
    axis: '#94a3b8',
    comparison: '#cbd5e1',
  },
  typography: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontFamilyMono: "ui-monospace, 'SF Mono', Menlo, monospace",
    size: {
      xs: 11,
      sm: 12,
      base: 14,
      md: 16,
      lg: 20,
      xl: 24,
      '2xl': 28,
      '3xl': 32,
    },
    weight: {
      light: 300,
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    scale: {
      display: {
        lg: { fontSize: 32, lineHeight: 38, fontWeight: 800, letterSpacing: -0.8 },
        md: { fontSize: 28, lineHeight: 34, fontWeight: 700, letterSpacing: -0.6 },
        sm: { fontSize: 24, lineHeight: 30, fontWeight: 700, letterSpacing: -0.4 },
      },
      heading: {
        lg: { fontSize: 20, lineHeight: 26, fontWeight: 700 },
        md: { fontSize: 17, lineHeight: 23, fontWeight: 600 },
        sm: { fontSize: 15, lineHeight: 21, fontWeight: 600 },
      },
      body: {
        lg: { fontSize: 15, lineHeight: 22 },
        md: { fontSize: 14, lineHeight: 21 },
        sm: { fontSize: 13, lineHeight: 19 },
        xs: { fontSize: 12, lineHeight: 17 },
      },
      label: {
        md: { fontSize: 12, lineHeight: 16, fontWeight: 600 },
        sm: { fontSize: 11, lineHeight: 14, fontWeight: 600 },
      },
      amount: {
        hero: { fontSize: 32, lineHeight: 38, fontWeight: 800, letterSpacing: -1 },
        lg: { fontSize: 22, lineHeight: 28, fontWeight: 700 },
        md: { fontSize: 16, lineHeight: 22, fontWeight: 700 },
        stat: { fontSize: 26, lineHeight: 32, fontWeight: 800, letterSpacing: -0.6 },
      },
    },
  },
  space: {
    '1': 4,
    '2': 8,
    '3': 12,
    '4': 16,
    '5': 20,
    '6': 24,
    '8': 32,
    '10': 40,
    '12': 48,
    '16': 64,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    card: 20,
    button: 14,
    pill: 999,
    control: 6,
  },
  shadow: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    card: '0 1px 3px rgba(26, 29, 41, 0.06), 0 1px 2px rgba(26, 29, 41, 0.04)',
  },
  layout: {
    phoneWidth: 393,
    phoneHeight: 852,
    screenPadding: 20,
    tabBarHeight: 84,
    headerHeight: 96,
  },
  touchTarget: {
    min: 44,
  },
  categoryIcons: {
    expense: {
      comida: '🍔',
      supermercado: '🛒',
      transporte: '🚗',
      compras: '📦',
      entretenimiento: '🎬',
      servicios: '⚡',
      salud: '💊',
      educacion: '🎓',
      hogar: '🏠',
      otros: '✨',
    },
    income: {
      sueldo: '💼',
      freelance: '💻',
      'ingresos-extra': '💰',
      inversiones: '📈',
      bonos: '🎊',
      otros: '✨',
    },
    uncategorized: '❓',
  },
} as const;

/**
 * Component geometry read off the `mu-*` CSS in `design/mockups/mobile/index.html`, namespaced
 * per primitive. This is **not** parity-tested against `design/tokens.json` — it deliberately
 * holds values that never graduate to a design token (border widths, control sizing, glyph
 * sizes, letter-spacing/line-height overrides) per the plan's Decision 2 and its "Values
 * deliberately NOT promoted to tokens.json" table.
 *
 * Convention: a value here is used whenever the corresponding mockup rule sets a **bare**
 * pixel/number literal. When a mockup rule instead reads `var(--sp4)` / `var(--r-lg)` / etc.,
 * the primitive consumes the matching `theme` constant directly instead of duplicating it here.
 *
 * `lineHeight` values that come from a unitless CSS `line-height` multiplier are pre-computed
 * to points (`fontSize * multiplier`, rounded to the nearest integer) because React Native's
 * `lineHeight` style is an absolute value, not a multiplier. The comment on each entry shows
 * the source multiplier and the arithmetic.
 *
 * Graduation rule (recorded in `docs/best-practices/stack/design-tokens.md`): a value here
 * graduates to `design/tokens.json` when it is a colour, or when two unrelated primitives use
 * the same value for the same semantic reason.
 */
export const componentMetrics = {
  /** Shared border widths — 19 `mu-*` rules use one of these two values. */
  borderWidth: {
    /** `.mu-card` (L296), `.mu-badge` (L370), `.mu-pill` (L395), `.mu-tx` (L472), `.mu-note` (L554), `.mu-tabbar` (L538) and 13 other 1px borders. */
    hairline: 1,
    /** `.mu-input` (L416), `.mu-chip` (L381), `.mu-check` (L432). */
    control: 1.5,
  },

  /** Shared shadow decompositions. React Native's shadow API takes a flat `shadowColor` +
   * `shadowOpacity` + `shadowRadius` + `shadowOffset`, so each `theme.shadow.*` CSS
   * `box-shadow` string decomposes to its first layer's offset-y/radius/opacity here, reused by
   * every primitive whose mockup rule reads the same `var(--sh-*)`. */
  shadow: {
    /** Pure black — matches `theme.shadow.sm`'s `rgba(0, 0, 0, α)` tint. */
    black: '#000000',
    /** `theme.shadow.sm` (`0 1px 2px 0 rgba(0, 0, 0, 0.05)`) — used by `.mu-tx`
     * (`--sh-sm`, L472), `.mu-switch::after` (L447), `.mu-segment__item.is-active` (L408).
     * `elevation` is the Android-only equivalent React Native reads instead of the
     * `shadow*` properties above; not part of the CSS token, kept alongside it so every
     * consumer sources the whole shadow from one place. */
    sm: { offsetY: 1, radius: 2, opacity: 0.05, elevation: 1 },
    /** `theme.shadow.card`'s first layer (`0 1px 3px rgba(26, 29, 41, 0.06)`) — used by
     * `.mu-card` (`--sh-card`, L296). The rgba tint (26, 29, 41) is `theme.colors.textPrimary`. */
    card: { offsetY: 1, radius: 3, opacity: 0.06, elevation: 1 },
  },

  text: {
    /** `.mu-h1` (L322): letterSpacing -.7px; lineHeight 28 * 1.18 = 33.04 → 33. */
    h1: { letterSpacing: -0.7, lineHeight: 33 },
    /** `.mu-h2` (L323): letterSpacing -.3px; lineHeight 20 * 1.25 = 25. */
    h2: { letterSpacing: -0.3, lineHeight: 25 },
    /** `.mu-h3` (L324): letterSpacing -.2px; no line-height override in the mockup. */
    h3: { letterSpacing: -0.2 },
    /** `.mu-p` (L325): lineHeight 14 * 1.55 = 21.7 → 22. */
    body: { lineHeight: 22 },
    /** `.mu-p--lead` (L326), composed with `.mu-p`'s line-height: fontSize 15 (bare literal); lineHeight 15 * 1.55 = 23.25 → 23. */
    bodyLead: { fontSize: 15, lineHeight: 23 },
    /** `.mu-eyebrow` (L329-331): letterSpacing .1em over an 11px (`--xs`) font ≈ 1.1pt. */
    eyebrow: { letterSpacing: 1.1 },
    /** `.mu-label` (L412): margin-bottom 6px. */
    label: { marginBottom: 6 },
    /** `.mu-hint` (L422): margin-top 6px. */
    hint: { marginTop: 6 },
    /** `.mu-mono` (L579): letterSpacing -.2px. */
    mono: { letterSpacing: -0.2 },
  },

  button: {
    /** `.mu-btn` (L349) min-height. */
    height: 52,
    /** `.mu-btn--sm` (L360) min-height. */
    heightSm: 40,
    /** `.mu-btn--ghost` (L357) min-height. */
    heightGhost: 44,
    /** `.mu-btn` (L351) font-size (bare literal, not `--base`/`--md`). */
    fontSize: 15,
    /** `.mu-btn` (L351) letter-spacing. */
    letterSpacing: -0.1,
    /** Not in the mockup CSS (`disabled` is a React Native-only state, no `.mu-btn` equivalent)
     * — the dimming amount `Button` applies when `disabled` is true. */
    disabledOpacity: 0.55,
  },

  card: {
    /** `.mu-card__sub` (L302) margin-top. */
    subMarginTop: 2,
    /** `.mu-card__title` (L301) letter-spacing. */
    titleLetterSpacing: -0.2,
  },

  hero: {
    /** `.mu-hero__icon` (L315) width/height. */
    iconSize: 52,
    /** `.mu-hero__icon` (L316) glyph font-size. */
    iconGlyphSize: 26,
    /** `.mu-hero::after` (L310) decoration width/height. */
    decorationSize: 130,
    /** `.mu-hero::after` (L310) decoration right/top offset. */
    decorationOffset: -30,
    /** `.mu-hero__title` (L318) letter-spacing. */
    titleLetterSpacing: -0.4,
    /** `.mu-hero__sub` (L319) margin-top. */
    subMarginTop: 2,
    /** `.mu-hero` (L305-308) has no explicit CSS height — it is content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS`: 2 × vertical padding (`--sp5` = 20) + the
     * icon size (52) = 92. */
    minTouchHeight: 92,
  },

  badge: {
    /** `.mu-badge` (L368) vertical padding. */
    paddingVertical: 3,
    /** `.mu-badge` (L368) horizontal padding. */
    paddingHorizontal: 9,
    /** `.mu-badge` (L368) icon/label gap. */
    gap: 4,
  },

  categoryChip: {
    /** `.mu-chip` (L380) min-height. */
    minHeight: 74,
    /** `.mu-chip` (L379) inner (emoji/label/hint) gap. */
    gap: 3,
    /** `.mu-chip__emoji` (L384) font-size. */
    emojiSize: 22,
    /** `.mu-chip__emoji` (L384): unitless line-height 1 → equal to font-size. */
    emojiLineHeight: 22,
    /** `.mu-chip__star` (L389) width/height. */
    starSize: 24,
    /** `.mu-chip__star` (L389) top/right offset. */
    starOffset: -8,
    /** `.mu-chip__star` (L390) glyph font-size. */
    starFontSize: 12,
  },

  statTile: {
    /** `.mu-stat__value` (L492) margin-top. */
    valueMarginTop: 6,
    /** `.mu-stat__sub` (L493) margin-top. */
    subMarginTop: 4,
    /** `.mu-stat__arrow` (L494) font-size. */
    arrowFontSize: 15,
  },

  note: {
    /** `.mu-note` (L554): unitless line-height 1.5 over a 12px (`--sm`) font = 18. */
    lineHeight: 18,
    /** `.mu-note__icon` (L559) font-size. */
    iconFontSize: 17,
    /** `.mu-note__icon` (L559): unitless line-height 1.3 * 17 = 22.1 → 22. */
    iconLineHeight: 22,
    /** Home-screen implementation plan (issue #12), Decision-adjacent (found in review): no
     * `.mu-note` action equivalent is drawn in the mockup — `sync-error`'s "Reintentar" is drawn
     * as inline text, not a separate control. Rendered here as its own sibling `Pressable`
     * instead (accessibility, real touch target), so this spacing value is a new decision, not a
     * measured one. */
    actionMarginTop: 6,
  },

  transactionRow: {
    /** `.mu-tx__icon` (L478) font-size. */
    iconFontSize: 20,
    /** `.mu-tx__icon` (L478) width. */
    iconWidth: 30,
    /** `.mu-tx__name` (L480) font-size (bare literal). */
    nameFontSize: 15,
    /** `.mu-tx__name` (L480): unitless line-height 1.25 * 15 = 18.75 → 19. */
    nameLineHeight: 19,
    /** `.mu-tx__meta` (L481) margin-top. */
    metaMarginTop: 1,
    /** `.mu-tx--excluded` (L477) opacity. */
    excludedOpacity: 0.55,
    /** `.mu-tx` (L469-474) has no explicit CSS height — it is content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS`: 2 × vertical padding (`--sp3` = 12) + the
     * name line (19) + `metaMarginTop` (1) + the meta line (`--sm` 12 × the inherited 1.5
     * line-height = 18) = 62. */
    minTouchHeight: 62,
  },

  textField: {
    /** `.mu-input` (L415) min-height. */
    height: 52,
    /** `.mu-input` (L416) font-size (bare literal). */
    fontSize: 15,
    /** `.mu-input.is-focus` (L419) focus-ring spread width. */
    focusRingWidth: 3,
  },

  checkbox: {
    /** `.mu-check` (L432) width/height. */
    size: 22,
    /** `.mu-check` (L433) checkmark glyph font-size. */
    checkGlyphFontSize: 13,
  },

  radio: {
    /** `.mu-radio` (L437) width/height. */
    size: 22,
    /** `.mu-radio` (L437) border width — distinct from `borderWidth.control`. */
    borderWidth: 2,
    /** `.mu-radio.is-on::after` (L441) inner dot size. */
    dotSize: 11,
  },

  switchControl: {
    /** `.mu-switch` (L443) width. */
    width: 46,
    /** `.mu-switch` (L443) height. */
    height: 27,
    /** `.mu-switch::after` (L446) thumb width/height. */
    thumbSize: 21,
    /** `.mu-switch::after` (L446) thumb top/left inset. */
    thumbInset: 3,
    /** `.mu-switch.is-on::after` (L450) thumb translateX when on. */
    thumbTranslateX: 19,
  },

  segment: {
    /** `.mu-segment` (L402) padding. */
    padding: 3,
    /** `.mu-segment` (L402) item gap. */
    gap: 2,
    /** `.mu-segment__item` (L405) vertical padding. */
    itemPaddingVertical: 6,
    /** `.mu-segment__item` (L405) horizontal padding. */
    itemPaddingHorizontal: 16,
    /** `.mu-segment__item` (L404-406) has no explicit CSS height — it is content-driven.
     * Conservative touch-target estimate for `TOUCH_METRICS`: 2 × `itemPaddingVertical` (6) +
     * the label line (`--sm` 12 × the inherited 1.5 line-height = 18) = 30. */
    itemMinTouchHeight: 30,
  },

  pill: {
    /** `.mu-pill` (L395) vertical padding. */
    paddingVertical: 7,
    /** `.mu-pill` (L395) horizontal padding. */
    paddingHorizontal: 14,
    /** `.mu-pill` (L394-397) has no explicit CSS height — it is content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS`: 2 × `paddingVertical` (7) + the label line
     * (`--sm` 12 × the inherited 1.5 line-height = 18) = 32. */
    minTouchHeight: 32,
  },

  overlay: {
    /** `.mu-overlay` (L522) stacking order above the screen content. */
    zIndex: 40,
  },

  sheet: {
    /** `.mu-sheet__grab` (L530) grab-handle width. */
    grabWidth: 40,
    /** `.mu-sheet__grab` (L530) grab-handle height. */
    grabHeight: 4,
    /** `.mu-sheet` (L528): max-height 78% of the overlay. */
    maxHeightPercent: 78,
  },

  modal: {
    /** `.mu-modal__icon` (L532) font-size. */
    iconFontSize: 34,
  },

  tabBar: {
    /** `.mu-tabbar__icon` (L546) width. */
    itemIconWidth: 46,
    /** `.mu-tabbar__icon` (L546) height. */
    itemIconHeight: 30,
    /** `.mu-tabbar__icon` (L546) glyph font-size. */
    itemIconFontSize: 18,
    /** `.mu-tabbar__item` (L541) icon/label gap. */
    itemGap: 4,
    /** `.mu-tabbar__item` (L540-544) has no explicit CSS height — it fills the tab bar's own
     * height (`theme.layout.tabBarHeight`, 84). Conservative touch-target estimate for
     * `TOUCH_METRICS`, scoped to the item's own icon+label stack: `itemIconHeight` (30) +
     * `itemGap` (4) + the label line (`--xs` 11 × the inherited 1.5 line-height = 16.5 → 17)
     * = 51. */
    itemMinTouchHeight: 51,
  },

  progress: {
    /** `.mu-progress` (L517) height. */
    height: 6,
    /** Home-screen implementation plan (issue #12) Decision 10: no `.mu-progress` equivalent in
     * the mockup CSS (there is no indeterminate state drawn there) — this is a new decision, not
     * a measured value, kept here for consistency with every other sizing/timing value this item
     * added (`bankRow`, `categoryRow`, `screenHeader`, `lineChart`, `legend`) rather than as a
     * component-local constant (found in review). Fraction of the track width the indeterminate
     * fill occupies while sweeping — matches the mockup's first-sync block's static `width:45%`,
     * which this animation replaces with continuous motion rather than a fixed, meaningless
     * number. */
    indeterminateFillFraction: 0.45,
    indeterminateSweepMs: 1200,
  },

  steps: {
    /** `.mu-steps__step` (L566) height. */
    height: 4,
    /** `.mu-steps` (L565) step gap. */
    gap: 6,
  },

  dots: {
    /** `.mu-dots__dot` (L563) size. */
    size: 7,
    /** `.mu-dots__dot.is-on` (L564) active-dot width. */
    activeWidth: 22,
    /** `.mu-dots` (L562) dot gap. */
    gap: 6,
  },

  emptyState: {
    /** `.mu-empty__icon` (L561) font-size. */
    iconFontSize: 42,
  },

  screenHeader: {
    /** `.mu-head__avatar` width/height. */
    avatarSize: 46,
    /** `.mu-head__avatar` glyph font-size. */
    avatarGlyphSize: 22,
    /** `.mu-head__action` width/height. */
    actionSize: 40,
    /** `.mu-head__action` glyph font-size. */
    actionGlyphFontSize: 18,
    /** `.mu-head__action--dot::after` (implementation plan for issue #15, Decision 11)
     * width/height. */
    actionDotSize: 8,
    /** `.mu-head__action--dot::after` top/right offset. */
    actionDotOffset: 2,
    /** `.mu-head__title`: letter-spacing -.5px; unitless line-height 1.15 over `--xl` (24px) =
     * 27.6 -> 28. */
    titleLetterSpacing: -0.5,
    titleLineHeight: 28,
    /** `.mu-head__sub` margin-top. */
    subMarginTop: 1,
    /** `.mu-head` (L250-253) top/bottom padding is a bare `52px … var(--sp4)` in the mockup —
     * `52` simulates a status bar inside the mockup's own browser chrome. The app instead wraps
     * the route in `SafeAreaView` (`edges: ['top']`, the pattern item #8 established), so
     * `ScreenHeader` itself only needs the *bottom* half of that padding, applied on both edges
     * once the safe area is already accounted for. */
    paddingVertical: 16,
    /** `.mu-head` (L250-253) has no explicit CSS height — content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS.headerAction`, scoped to the action button only:
     * its own `actionSize` (40) already carries the estimate. */
  },

  categoryRow: {
    /** `.mu-cat-row__icon` (L507) font-size. */
    iconFontSize: 18,
    /** `.mu-cat-row__icon` (L507) width. */
    iconWidth: 26,
    /** `.mu-cat-row` (L505) vertical padding. */
    paddingVertical: 12,
    /** `.mu-cat-row__bar` (L508) height. */
    barHeight: 6,
    /** `.mu-cat-row__bar` (L508) margin-top. */
    barMarginTop: 5,
    /** `.mu-cat-row` (L505-509) has no explicit CSS height — content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS`: 2 × `paddingVertical` (12) + the title/amount
     * row (`--small` 12 × the inherited 1.5 line-height = 18) + `barHeight` (6) + `barMarginTop`
     * (5) + the meta line (`--xs` 11 × the inherited 1.5 line-height = 16.5 -> 17) = 82. */
    minTouchHeight: 82,
  },

  lineChart: {
    /** `.mu-line` (L497) height. */
    height: 132,
    /** The mockup's gridlines (`index.html` home section) and current-month polyline stroke
     * widths. */
    gridStrokeWidth: 1,
    seriesStrokeWidth: 2.5,
    comparisonStrokeWidth: 2,
    comparisonDashArray: [4, 4],
  },

  legend: {
    /** `.mu-legend__dot` (L501) width/height. */
    dotSize: 9,
    /** `.mu-legend__dot` (L501) border-radius — a rounded square, not a circle, at this size. */
    dotRadius: 3,
    /** `.mu-legend__row` (L500) reads `gap:var(--sp2)` — consumed as `theme.space['2']` directly
     * at the call site, per the "bare literal vs. `var(--…)`" convention above; listed here only
     * so the mapping is discoverable from this file. */
  },

  /** `.mu-donut` (dashboard implementation plan for issue #17, Decision 8). */
  donutChart: {
    /** `.mu-donut` display width/height (bare literal). */
    size: 132,
    /** The `<svg viewBox="0 0 42 42">` coordinate space every `.mu-donut` in the mockup draws. */
    viewBoxSize: 42,
    /** The `<circle r="15.9">` radius (bare literal) — chosen upstream in the mockup so
     * `2 * PI * r` is close enough to `100` that a bucket's `stroke-dasharray`/`stroke-dashoffset`
     * can be expressed directly in percent-of-100 units instead of true arc length. */
    radius: 15.9,
    /** `<circle stroke-width="7">` (bare literal). */
    strokeWidth: 7,
  },

  /** `.mu-bars` (dashboard implementation plan for issue #17, Decision 8). */
  barChart: {
    /** `.mu-bars` (L496) height. */
    height: 120,
    /** `.mu-bars` (L496) column gap, and `.mu-bars__col` (L497) internal bar/label gap — both
     * read the same bare `6px` literal in the mockup. */
    gap: 6,
    /** `.mu-bars__bar` (L498) border-radius — asymmetric (rounded top, near-square bottom). */
    barRadiusTop: 6,
    barRadiusBottom: 2,
    /** `.mu-bars__lbl` (L501) font-size (bare literal). */
    labelFontSize: 10,
  },

  topBar: {
    /** `.mu-topbar__btn` (L286-289) width/height. */
    buttonSize: 36,
    /** `.mu-topbar__btn` (L286-289) glyph font-size. */
    buttonGlyphFontSize: 20,
  },
  bankRow: {
    /** `.mu-bank__logo` (L568) width/height. */
    logoSize: 40,
    /** `.mu-bank__logo` (L568) monogram letter-spacing. */
    monogramLetterSpacing: -0.3,
    /** `.mu-bank__name` (L572) font-size (bare literal). */
    nameFontSize: 15,
    /** `.mu-item__sub` (L459) margin-top. */
    subMarginTop: 1,
    /** `.mu-item__chev` (L460) font-size. */
    chevronFontSize: 18,
    /** `.mu-bank` (L562-566) has no explicit CSS height — content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS`, mirroring `transactionRow.minTouchHeight`'s
     * derivation: 2 × vertical padding (`--sp3` = 12) + the name line (19) + `subMarginTop` (1) +
     * the sub line (`--sm` 12 × the inherited 1.5 line-height = 18) = 62. */
    minTouchHeight: 62,
  },
  /** `.mu-item`, `__icon`, `__title` (settings implementation plan for issue #19, Decision 12).
   * `.mu-item__chev`, `__sub`, `__txt` are already `componentMetrics.bankRow` (owned jointly with
   * `CategoryRow`/`BankRow` since item #12/#9) — `ListRow` reuses those literals rather than
   * duplicating them under a second name. */
  listRow: {
    /** `.mu-item__icon` (L459-462) width/height. */
    iconSize: 40,
    /** `.mu-item__icon` (L461) glyph font-size. */
    iconGlyphSize: 19,
    /** `.mu-item__title` (L464) font-size (bare literal). */
    titleFontSize: 15,
    /** `.mu-item` (L454-457) has no explicit CSS height — content-driven. Conservative
     * touch-target estimate for `TOUCH_METRICS`: 2 × vertical padding (`--sp4` = 16) + the icon
     * size (40, which dominates the title+sub text stack) = 72. */
    minTouchHeight: 72,
  },
  /** `CategoryReorderList`'s `☰` drag handle (implementation plan for issue #21, Decision 10) —
   * drag-to-reorder is undrawn in the mockup, so these are conservative values rather than a
   * measured CSS rule. The icon grid's gap reuses `theme.space['2']` directly (the mockup's
   * `.mu-grid-3 { gap: var(--sp2) }`, L339) — the same "consumed directly, not duplicated here"
   * convention `Legend`'s `.mu-legend__row` gap already established above. */
  categoryReorderRow: {
    /** The handle's square touch box, sized like `TopBar`'s back button
     * (`componentMetrics.topBar.buttonSize`) so `withMinTarget` gives it the same treatment. */
    handleSize: 36,
    /** Elevation applied to the row being dragged, so it visually lifts above its siblings. */
    dragElevation: 6,
  },
} as const;

/**
 * Screen-level measured values, read off the mockup's `mu-*` CSS the same way `componentMetrics`
 * is, but namespaced per **screen** rather than per `components/ui/` primitive (implementation
 * plan for issue #8, Decision 10).
 *
 * `componentMetrics` cannot host these: every one of its groups is named after a
 * `components/ui/` primitive, and `theme` itself cannot grow a group —
 * `theme-tokens-parity.test.ts` asserts `Object.keys(theme).sort()` equals an exact ten-group
 * allowlist mirrored from `design/tokens.json`. `screenMetrics` is a sibling export with the same
 * doc-comment contract and the same graduation rule as `componentMetrics`: a value here graduates
 * to `design/tokens.json` when it is a colour, or when two unrelated surfaces use it for the same
 * semantic reason. This sets the pattern for every later screen item (#12–#21).
 */
export const screenMetrics = {
  onboarding: {
    /** `#s-onboarding-intro` (L702), `#s-onboarding-value` (L723/728/733),
     *  `#s-onboarding-ready` (L1095) hero glyph font-size. */
    heroGlyphSize: 62,
    /** `#s-onboarding-ready` summary-row glyph font-size (L1101-1102). */
    summaryGlyphSize: 20,
  },
  categorization: {
    /** `#s-stage-intro` (L1122) hero glyph font-size. */
    stageIntroHeroGlyphSize: 56,
    /** `#s-stage-intro` (L1132-1134) three-step icon font-size. */
    threeStepIconSize: 22,
    /** `#s-categorize-complete` (L1377) celebration glyph font-size. */
    completionCelebrationGlyphSize: 60,
    /** `.mu-topbar__btn` (L286-289) width/height — also read off the inline
     * `style="width:36px"` trailing spacer on `#s-stage-intro` (L1118), which balances the
     * leading back button so the title stays centered. */
    topBarButtonSize: 36,
    /** `.mu-topbar__btn` (L288) glyph font-size (bare literal, not a `--*` token). */
    topBarButtonGlyphSize: 20,
    /** `.mu-item__chev` (L466) chevron glyph font-size (bare literal, not a `--*` token). */
    disclosureChevronSize: 18,
  },
  /** `#s-home` (implementation plan for issue #12, Layer-by-Layer — `apps/mobile/theme.ts`). */
  home: {
    /** `<svg class="mu-line" viewBox="0 0 300 120" …>` (index.html home section). Belongs here,
     * not `componentMetrics.lineChart`, because it is the trend card's own layout choice, not a
     * property of the `LineChart` primitive itself — a future consumer (#17) may choose a
     * different aspect ratio for the same primitive. */
    chartViewBoxWidth: 300,
    chartViewBoxHeight: 120,
    /** Three evenly-spaced horizontal gridlines (`y="30"`, `y="60"`, `y="90"` over a 120-tall
     * viewBox — quarter divisions). */
    chartGridLineCount: 3,
  },
  /** `#s-merchant-edit` (implementation plan for issue #14, Layer-by-Layer). */
  merchants: {
    /** `.mu-topbar__btn` (L286-289) width/height — the same shared top-bar button geometry every
     * other screen's own `screenMetrics.<screen>.topBarButtonSize` records (Decision 11's
     * per-screen-local-composition precedent: `mu-topbar*` is `deferred` in `mu-class-map.ts`). */
    topBarButtonSize: 36,
    /** `.mu-topbar__btn` (L288) glyph font-size. */
    topBarButtonGlyphSize: 20,
    /** `.mu-item__chev` (L466) disclosure-row chevron glyph font-size. */
    disclosureChevronSize: 18,
    /** `.mu-item__icon` (L459-462) width/height. */
    itemIconSize: 40,
    /** `.mu-item__icon` (L461) glyph font-size. */
    itemIconGlyphSize: 19,
    /** `.mu-item__title` (L464) font-size (bare literal, not a `--*` token). */
    itemTitleFontSize: 15,
    /** `.mu-item__sub` (L465) margin-top. */
    itemSubMarginTop: 1,
    /** `#s-merchant-edit`'s `.mu-bars` inline `style="height:80px"` override (L1343) — not the
     * class's own 120px default, which a different screen may use unmodified. */
    barsHeight: 80,
    /** `.mu-bars` / `.mu-bars__col` (L496-497) gap. */
    barsGap: 6,
    /** `.mu-bars__lbl` (L501) font-size. */
    barLabelFontSize: 10,
    /** `.mu-bars__bar` (L498) border-radius, top corners. */
    barRadiusTop: 6,
    /** `.mu-bars__bar` (L498) border-radius, bottom corners. */
    barRadiusBottom: 2,
    /** `.mu-grid-2` (category-picker) two-column grid — each chip's column width, as a
     * percentage string so `no-style-literals.test.ts`'s numeric-literal scanner never applies
     * to it (Scanner B only tracks bare numbers). */
    categoryPickerColumnWidth: '48%',
  },
  /** `#s-transactions` (implementation plan for issue #15, Layer-by-Layer). Most of what this
   * screen draws is already token-based (`.mu-pad`, `.mu-tx-group`'s `var(--sp*)` margins);
   * these are the few bare-literal values left, for the screen-local `mu-list`/`mu-item`
   * (`FilterToggleRow`, Decision 11 — deferred to #19, composed here without touching
   * `MU_CLASS_MAP`) and the sheet ✕ close button (`.mu-topbar__btn`, also still deferred). */
  transactions: {
    /** `.mu-item__title` (L464) font-size (bare literal). */
    filterToggleTitleFontSize: 15,
    /** `.mu-item__sub` (L465) margin-top. */
    filterToggleSubMarginTop: 1,
    /** `.mu-topbar__btn` (L286) width/height. */
    closeButtonSize: 36,
    /** `.mu-topbar__btn` (L286) glyph font-size. */
    closeButtonFontSize: 20,
  },
  /** `#s-transaction-detail` (implementation plan for issue #16, Layer-by-Layer). The screen-local
   * top bar mirrors #13's `StageTopBar` sizing (Decision 10 — `mu-topbar*` stays deferred). */
  transactionDetail: {
    /** The hero card's state glyph (🛒 / ❓ / 🚫), `font-size:34px` (bare literal). */
    heroGlyphSize: 34,
    /** `.mu-topbar__btn` width/height. */
    topBarButtonSize: 36,
    /** `.mu-topbar__btn` glyph font-size. */
    topBarButtonGlyphSize: 20,
  },
  /** `#s-bank-syncing` (implementation plan for issue #11). Its headline icon
   * (`<div style="font-size:52px">🔄</div>` in the progress states, `⚠️` in `error`) is a bare
   * inline style in the mockup, not a `mu-*` class, so `mu-class-map.ts` (V4) does not inventory
   * it — this is the screen's own layout choice, not a property of a shared primitive. Found
   * during implementation: the plan's Layer-by-Layer claimed no new `componentMetrics` group,
   * which held for every *class* this screen draws but missed this one inline literal. */
  bankSyncing: {
    headlineIconFontSize: 52,
  },
  /** `#s-settings-account`, `#s-settings-about` (implementation plan for issue #19,
   * Layer-by-Layer). Both blocks are bare inline styles in the mockup, not `mu-*` classes. */
  settings: {
    /** `#s-settings-account`'s 📱 device-avatar circle width/height (L2216). */
    accountDeviceAvatarSize: 64,
    /** Device-avatar 📱 glyph font-size (L2216). */
    accountDeviceAvatarGlyphSize: 28,
    /** `#s-settings-about`'s 💰 brand-block icon width/height (L2476). */
    aboutBrandIconSize: 74,
    /** Brand-block icon border-radius — a bare literal in the mockup, not a `--r-*` token
     * (L2476). */
    aboutBrandIconRadius: 20,
    /** Brand-block 💰 glyph font-size (L2476). */
    aboutBrandIconGlyphSize: 34,
  },
  /** `#s-dashboard` (implementation plan for issue #17, Decision 8, Layer-by-Layer). Belongs
   * here, not `componentMetrics.lineChart`, for the same reason `screenMetrics.home` does: the
   * trend card's aspect ratio is this screen's own layout choice, not a property of the
   * `LineChart` primitive itself. Reuses `home`'s exact `viewBox`/gridline count (both trend
   * cards draw a `300x120` chart with three gridlines), so this screen states no new geometry of
   * its own for the line chart. */
  dashboard: {
    chartViewBoxWidth: 300,
    chartViewBoxHeight: 120,
    chartGridLineCount: 3,
  },
  /** `#s-notifications-intro`, `#s-notifications-schedule`, `#s-settings-notifications`
   * (implementation plan for issue #18, Layer-by-Layer). */
  reminders: {
    /** `SamplePushCard`'s 💰 glyph, `<span style="font-size:20px">💰</span>` (`index.html:1005`). */
    samplePushGlyphSize: 20,
    /** `CustomTimeCard`'s two numeric boxes, `.mu-otp__box` inline `style="width:62px"`
     * (`index.html:1061`). Square, so this is also the box height. */
    customTimeBoxSize: 62,
    /** `TimePresetGrid`'s `.mu-grid-2` two-column layout — React Native has no CSS grid, so this
     * is the same percentage-column-width workaround `screenMetrics.merchants
     * .categoryPickerColumnWidth` already uses for the identical mockup class. */
    timeGridColumnWidth: '48%',
  },
} as const;
