import * as Crypto from 'expo-crypto';
import type { SQLiteDatabase } from 'expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';

import { ensureDatabaseReady, resetDatabaseBootstrap } from './bootstrap';
import { deleteAppDatabaseFile, openAppDatabase } from './client';
import type { DbPorts } from './ids';
import { type MigrationsConfig, resolveMigrationsConfig } from './migrations-config';
import type { AppDatabase } from './types';

// `drizzle/migrations.js` has no type declarations of its own — it is generated by `drizzle-kit`,
// not hand-written — so this mirrors `src/db/testing/memory-db.ts`'s `_journal.json` require.
// See `./migrations-config.ts` for why `resolveMigrationsConfig` (not a plain `.journal` read)
// is required here — issue #95.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const migrationsModule = require('../../drizzle/migrations') as
  | MigrationsConfig
  | { default: MigrationsConfig };
const migrations: MigrationsConfig = resolveMigrationsConfig(migrationsModule);

/**
 * The Expo-runtime assembly `ensureDatabaseReady()` (item #3) has needed since it merged, but had
 * no caller in `app/` until this item (implementation plan Decision 1; Verification Log —
 * `grep -rn "ensureDatabaseReady" apps/mobile/app` found zero hits at the plan revision).
 *
 * Opens the on-device database once per process, wires `drizzle-orm/expo-sqlite/migrator` — its
 * `migrate<TSchema>(db, config): Promise<void>` signature was confirmed **genuinely async**
 * against `node_modules/drizzle-orm/expo-sqlite/migrator.d.ts` at implementation time (the plan
 * flagged this as unverified because `drizzle-orm` was not installed in the plan's `node_modules`
 * tree) — and supplies the `newId` / `now` ports from `expo-crypto` and the system clock.
 *
 * `getAppDatabase()` is the single app-tier entry point to the store. Feature hooks call it and
 * then call repository functions; screens call neither directly. This keeps `AGENTS.md`'s
 * layering (`app/ → feature hooks → src/db → SQLite`) and the `dbAccessBoundary` ESLint rule
 * intact — this is the one file in `src/db` allowed to import `expo-crypto`, and no file outside
 * `src/db` imports `drizzle-orm`, `expo-sqlite` or `better-sqlite3`.
 */

/** Reads the newest entry's tag from the journal `drizzle/migrations.js` already imports —
 * needed only for `DatabaseMigrationError`'s attribution message (`migrate.ts`), so no new file
 * read and no new bundler config is needed. */
function latestJournalTag(): string {
  const last = migrations.journal.entries.at(-1);
  if (!last) throw new Error('drizzle/migrations.js journal has no entries');
  return last.tag;
}

// Module-level single-flight promise, written once before any `await` (concurrent-event-source
// addendum): concurrent callers share one open+bootstrap rather than racing two. Cleared on
// failure so the next call genuinely retries instead of caching a permanent failure — mirroring
// `src/db/bootstrap.ts`'s own single-flight guard, which remains the inner one.
let handle: Promise<AppDatabase> | undefined;

// The raw `sqlite` handle behind the memoized `db` above, kept alongside it so
// `resetAppDatabase()` can close it before deleting the file (implementation plan for issue #19,
// Decision 3). Set the moment `openAppDatabase()` returns, before `ensureDatabaseReady` even
// starts — a wipe that races an in-flight bootstrap must still be able to close the real handle.
let sqliteHandle: SQLiteDatabase | undefined;

export function getAppDatabase(): Promise<AppDatabase> {
  if (!handle) {
    handle = (async () => {
      const { sqlite, db } = openAppDatabase();
      sqliteHandle = sqlite;
      await ensureDatabaseReady({
        db,
        migrate: () => migrate(db, migrations),
        latestMigrationTag: latestJournalTag(),
        newId: () => Crypto.randomUUID(),
        now: () => new Date().toISOString(),
      });
      return db;
    })().catch((error: unknown) => {
      handle = undefined;
      sqliteHandle = undefined;
      throw error;
    });
  }
  return handle;
}

/** Test-only escape hatch: clears the memoized handle so a test can force a fresh open. Not
 * exported for app use — this module is not exercised by the `db` Jest project (which uses
 * `src/db/testing/memory-db.ts` instead), but the reset hook is kept for symmetry with
 * `bootstrap.ts`'s `__resetBootstrapForTests`. */
export function __resetAppDatabaseForTests(): void {
  handle = undefined;
  sqliteHandle = undefined;
}

/**
 * The **only** sanctioned way to invalidate the memoized database handle (implementation plan
 * for issue #19, Decision 3) — the last step of `wipeLocalData`'s ordered sequence
 * (`src/features/settings/wipe-local-data.ts`), run only after every credential key has been
 * confirmed deleted from the secure store.
 *
 * Order matters and is deliberately not the mirror image of `getAppDatabase()`'s own assembly:
 * the memo is cleared **before** the file deletion is even awaited, so a caller that arrives
 * mid-wipe (a feature hook re-reading on focus, per the concurrent-event-source addendum) starts
 * a fresh `getAppDatabase()` call against a store that is about to be recreated, rather than
 * receiving a handle to a file that is about to disappear out from under it. If no handle has
 * ever been opened in this process (`sqliteHandle` is `undefined`), the file deletion is skipped
 * — there is nothing to close and `expo-sqlite`'s own deletion API does not require an existing
 * file, but skipping avoids depending on that being true forever.
 */
export async function resetAppDatabase(): Promise<void> {
  const sqlite = sqliteHandle;
  handle = undefined;
  sqliteHandle = undefined;
  if (sqlite !== undefined) {
    await deleteAppDatabaseFile(sqlite);
  }
  resetDatabaseBootstrap();
}

/**
 * The runtime `DbPorts` a person-initiated write (today: `insertManualTransaction`, implementation
 * plan for issue #15, Decision 12) supplies to a repository function — `expo-crypto`'s
 * `digestStringAsync` / `randomUUID` and the system clock, the same three concrete implementations
 * `getAppDatabase()`'s own bootstrap call above uses. This file is the one place in `src/db`
 * allowed to import `expo-crypto` (see the module doc comment); a feature hook builds its ports by
 * calling this function rather than importing `expo-crypto` itself.
 */
export function createRuntimePorts(): DbPorts {
  return {
    newId: () => Crypto.randomUUID(),
    now: () => new Date().toISOString(),
    digestSha256: (input: string) => Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, input),
  };
}
