import * as Crypto from 'expo-crypto';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';

import { ensureDatabaseReady } from './bootstrap';
import { openAppDatabase } from './client';
import type { AppDatabase } from './types';

// eslint-disable-next-line @typescript-eslint/no-require-imports -- mirrors
// `src/db/testing/memory-db.ts`'s `_journal.json` require; `drizzle/migrations.js` has no type
// declarations of its own and is generated by `drizzle-kit`, not hand-written.
const migrations = require('../../drizzle/migrations') as {
  journal: { entries: { tag: string }[] };
  migrations: Record<string, string>;
};

/**
 * The Expo-runtime assembly `ensureDatabaseReady()` (item #3) has needed since it merged, but had
 * no caller in `app/` until this item (implementation plan Decision 1; Verification Log —
 * `grep -rn "ensureDatabaseReady" apps/mobile/app` found zero hits at the plan revision).
 *
 * Opens the on-device database once per process, wires `drizzle-orm/expo-sqlite/migrator` — its
 * `migrate<TSchema>(db, config): Promise<void>` signature was confirmed **genuinely async**
 * against `node_modules/drizzle-orm/expo-sqlite/migrator.d.ts` at implementation time (the plan
 * flagged this as unverified because `drizzle-orm` was not installed in the plan's `node_modules`
 * tree) — and supplies the `newId` / `now` ports from `expo-crypto` and the system clock.
 *
 * `getAppDatabase()` is the single app-tier entry point to the store. Feature hooks call it and
 * then call repository functions; screens call neither directly. This keeps `AGENTS.md`'s
 * layering (`app/ → feature hooks → src/db → SQLite`) and the `dbAccessBoundary` ESLint rule
 * intact — this is the one file in `src/db` allowed to import `expo-crypto`, and no file outside
 * `src/db` imports `drizzle-orm`, `expo-sqlite` or `better-sqlite3`.
 */

/** Reads the newest entry's tag from the journal `drizzle/migrations.js` already imports —
 * needed only for `DatabaseMigrationError`'s attribution message (`migrate.ts`), so no new file
 * read and no new bundler config is needed. */
function latestJournalTag(): string {
  const last = migrations.journal.entries.at(-1);
  if (!last) throw new Error('drizzle/migrations.js journal has no entries');
  return last.tag;
}

// Module-level single-flight promise, written once before any `await` (concurrent-event-source
// addendum): concurrent callers share one open+bootstrap rather than racing two. Cleared on
// failure so the next call genuinely retries instead of caching a permanent failure — mirroring
// `src/db/bootstrap.ts`'s own single-flight guard, which remains the inner one.
let handle: Promise<AppDatabase> | undefined;

export function getAppDatabase(): Promise<AppDatabase> {
  if (!handle) {
    handle = (async () => {
      const { db } = openAppDatabase();
      await ensureDatabaseReady({
        db,
        migrate: () => migrate(db, migrations),
        latestMigrationTag: latestJournalTag(),
        newId: () => Crypto.randomUUID(),
        now: () => new Date().toISOString(),
      });
      return db;
    })().catch((error: unknown) => {
      handle = undefined;
      throw error;
    });
  }
  return handle;
}

/** Test-only escape hatch: clears the memoized handle so a test can force a fresh open. Not
 * exported for app use — this module is not exercised by the `db` Jest project (which uses
 * `src/db/testing/memory-db.ts` instead), but the reset hook is kept for symmetry with
 * `bootstrap.ts`'s `__resetBootstrapForTests`. */
export function __resetAppDatabaseForTests(): void {
  handle = undefined;
}
