module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    // Inlines the `.sql` migration files that `drizzle/migrations.js` imports (generated by
    // `drizzle-kit generate` under `driver: 'expo'`) as strings at bundle time, paired with the
    // `sql` entry added to `resolver.sourceExts` in `metro.config.js`.
    plugins: [['babel-plugin-inline-import', { extensions: ['.sql'] }]],
  };
};
